### ISSUE TITLE
Please add support for Julia 1.7 running on Apple Silicon (ARM64) on MacOS

### ISSUE THREAD

**Issue by abhayap** [JuliaIO/MAT.jl#168]
It would be great if this supported Apple Silicon natively.

**Comment by johnnychen94** [comment]
This needs upstream support, please subscribe https://github.com/JuliaIO/HDF5.jl/issues/870

**Comment by abhayap** [comment]
Thanks @johnnychen94

**Comment by abhayap** [comment]
@johnnychen94 I installed HDF5 via Homebrew. Is there a way I can use that with the MAT package?

**Comment by ajalexei** [comment]
Check out the "Using custom or system provided HDF5 binaries" section on the HDF5.jl webpage: you can set the environment vartiable JULIA_HDF5_PATH to point to the location of the library file. More generically you can use the override mechanism provided by the julia packaging system to force the usage of the system provided libraries.

**Comment by musm** [comment]
We've just tagged 0.16 which adds apple silicon support, this will now allow up to upgrade this package and close this issue out. Fix should be available soon.

**Comment by abhayap** [comment]
Thanks @musm! This works for me now.
