### ISSUE TITLE
Compatibility with Julia 1.10 and HDF5 0.17+

### ISSUE THREAD

**Issue by truedichotomy** [JuliaIO/MAT.jl#188]
Currently, MAT.jl is not compatible with Julia 1.10 DEV. I believe that's mainly due to HDF5 being incompatible currently, but there could also be a versioning issue.

**Comment by musm** [comment]
This seems like an issue for HDF5.jl not MAT.jl, it'll be fixed, can't guarantee when, but since  Julia 1.10 is DEV it is not a high priority.
