### ISSUE TITLE
Superfluous error when parsing old-style class object in v7.3

### ISSUE THREAD

**Issue by Jeroen-van-der-Meer** [JuliaIO/MAT.jl#197]
If you save an old-style Matlab object (i.e. created in an `@ClassName` folder, before `classdef` was a thing) in a `v7.3` file, `MAT.jl` throws an error saying it cannot read from a non-struct group (cf. line 232 of `MAT_HDF5.jl`). As a matter of fact, it appears that Matlab saves these objects 'as if' they are structs, and indeed the objects that I have appear to be read just fine if I manually remove the error and let the code continue.

Instead of throwing an error, I would propose giving a warning, such as

```julia
@warn "Unknown non-struct group of type $mattype detected; attempting to read as struct"
```

cf. also associated [PR](https://github.com/JuliaIO/MAT.jl/pull/198)

**Comment by musm** [comment]
closed by https://[github.com/JuliaIO/MAT.jl/pull/198](https://github.com/JuliaIO/MAT.jl/pull/198)
