### ISSUE TITLE
MAT level 4 support

### ISSUE THREAD

**Issue by simonster** [JuliaIO/MAT.jl#4]
We currently support only MAT level 5, but MAT level 4 shouldn't be too hard

**Comment by vsaase** [comment]
see #132

**Comment by AnHeuermann** [comment]
I would be interested in MAT v4 support as well.

We have a tool ([OpenModelica](https://openmodelica.org/) / [OMJulia.jl](https://github.com/OpenModelica/OMJulia.jl)) that is generating mat v4 result files, that I would like to open and manipulate in Julia.

It seems like #132 is stuck. There is also a different PR in #164 that may be related to this issue.
Is there any way one could help with the PR?
