### ISSUE TITLE
write vs. reshape on Julia 0.5.0_  

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaIO/MAT.jl#58]
Hi,

on 0.5.0-dev+4426 (Win64),  writing a reshaped array does not work. See example below. Thanks for having a look at it. /Paul S

using MAT
C1   = reshape(1:40,5,8) + 0
C2   = reshape(1:40,5,8)

fh = matopen("MatFile1.mat","w")               #works
write(fh,"C1",C1)
close(fh)

fh = matopen("MatFile2.mat","w")               #crashes
write(fh,"C2",C2)
close(fh)

**Comment by timholy** [comment]
@PaulSoderlind, thanks for the bug report. It's also fair to say that julia-0.5 is still in "use it as long as you're comfortable fixing package bugs yourself" mode---if that's not the case, consider using julia-0.4.

Or, a pull request to MAT.jl fixing this would be greatly appreciated :wink:.

**Comment by PaulSoderlind** [comment]
Thanks, I am indeed using 0.4.5 on a regular basis. Very nice language, by the way. 

More recently, I have tried out some of my code on 0.5, with two aims: preparing for the inevitable (...), but also contributing to the language in the best way I can (submitting bug reports). Not a developer, just a user.  /Paul S

**Comment by musm** [comment]
stale
