### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by DatName** [JuliaIO/MAT.jl#62]
I seem to have a memory leak. The following steps should reproduce the problem.

Create a data structure in matlab via
`testData = struct('asString', 'aaaa', 'asFloat64', 122, 'asAnotherFloat64', 22)`
then save it:
`save('D:\\testdata.mat', '-struct', 'testData')`
then run the following code in julia:

```
using MAT

function thyTest()::Void

    for j::Int64 = 1 : 100000
        matfile = matopen("D:\\testdata.mat")

        m_open::String  = read(matfile, "asString")
        m_high::Float64 = read(matfile, "asFloat64")
        m_low::Float64  = read(matfile, "asAnotherFloat64")

        close(matfile)
    end

    return nothing
end
```
then run` thyTest()` and `gc()`.
This leaves me with 3 Gb RAM usage by julia which can never be freed during its lifetime.

I'm running this under windows
julia version is 0.5
MAT version is 0.3.1

**Comment by simonster** [comment]
Probably the same issue as https://github.com/JuliaIO/HDF5.jl/issues/349

**Comment by musm** [comment]
fixed
