### ISSUE TITLE
Move package

### ISSUE THREAD

**Issue by simonster** [JuliaIO/MAT.jl#71]
This package should be moved to https://github.com/JuliaIO or https://github.com/JuliaInterop. Any feelings on which?

**Comment by timholy** [comment]
Either seems viable to me, but I think JuliaIO is probably better than JuliaInterop. The packages at JuliaInterop are more about *calling* other applications, whereas this is about file I/O.

**Comment by laurentheirendt** [comment]
JuliaIO :+1:

**Comment by simonster** [comment]
Moved.
